-
  db:
    username: root
    password: dockerpass
    host: 127.0.0.1
    port: 5012
    dbname: data
    destination_table_name: CPI_DEC_2022_Q_csv
  data:
    directory: ../data/
    filename: Consumers-price-index-December-2022-quarter-index-numbers
    extension: csv # only json, csv is acceptable for now
-
  db:
    username: root
    password: dockerpass
    host: 127.0.0.1
    port: 5012
    dbname: data
    destination_table_name: CPI_DEC_2022_Q_json
  data:
    directory: ../data/
    filename: Consumers-price-index-December-2022-quarter-index-numbers
    extension: json # only json, csv is acceptable for now